<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OPOL MHO - Patient Medical Record - {{ $patient->firstname ?? '' }} {{ $patient->lastname ?? '' }}</title>
    @vite('resources/css/app.css')
    <style>
        @page {
            size: A4 landscape;
            margin: 12mm;
        }

        @media print {
            .no-print { display: none !important; }
            body { background: #fff !important; }
            .report-shell {
                border: 0 !important;
                box-shadow: none !important;
                padding-bottom: 32px !important;
            }
            .print-page-footer {
                display: block !important;
            }
        }

        * {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
        }

        .num {
            font-variant-numeric: tabular-nums;
            text-align: right;
        }

        .print-page-footer {
            display: none;
            position: fixed;
            bottom: 6mm;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 7.5pt;
            color: #777;
            z-index: 1000;
        }
    </style>
</head>
<body class="min-h-screen bg-slate-100 text-slate-900">
    @unless ($embedded ?? false)
        <div class="no-print sticky top-0 z-10 bg-white/90 backdrop-blur border-b border-slate-200 px-4 py-3">
            <div class="max-w-7xl mx-auto flex items-center justify-between gap-3">
                <div class="text-sm font-semibold text-slate-900">Patient Medical Record</div>
                <button type="button" onclick="window.print()" class="px-3 py-2 rounded-xl bg-green-900 text-white text-[0.78rem] font-semibold hover:bg-green-800">Print / Save as PDF</button>
            </div>
        </div>
    @endunless

    <div class="max-w-7xl mx-auto p-4 md:p-6">
        <div class="report-shell bg-white border border-slate-200 rounded-3xl p-6 md:p-8">

            {{-- ===== LETTERHEAD ===== --}}
            <div class="border-b-4 border-double border-slate-900 pb-4">
                <div class="flex items-start gap-4">
                    <img src="{{ asset('images/MHOLogoV2.png') }}" alt="{{ $clinicName }} logo"
                         class="letterhead-logo w-16 h-16 object-contain flex-shrink-0 mt-0.5">

                    <div class="flex-1 min-w-0">
                        <div class="text-[0.78rem] font-semibold uppercase tracking-[0.35em] text-slate-500">
                            {{ $clinicName }}
                        </div>
                        <h1 class="mt-1 text-2xl font-bold tracking-wide text-slate-900">PATIENT MEDICAL RECORD</h1>
                    </div>
                </div>

                <div class="mt-5 grid grid-cols-1 md:grid-cols-4 gap-4 text-[0.84rem]">
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Patient Name</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $patient->firstname ?? '' }} {{ $patient->middlename ?? '' }} {{ $patient->lastname ?? '' }}</div>
                    </div>
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Patient ID</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $patient->user_id }}</div>
                    </div>
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Generated On</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $generatedOn->format('F j, Y') }}</div>
                        <div class="text-slate-600">{{ $generatedOn->format('g:i A') }}</div>
                    </div>
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Generated By</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $generatedBy }}</div>
                        <div class="text-slate-600">Administrator</div>
                    </div>
                </div>
            </div>

            {{-- ===== 1. REPORT INFORMATION ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">1. REPORT INFORMATION</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.84rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.72rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-4 font-semibold">Clinic Name</th>
                                <th class="py-2 pr-4 font-semibold">Report Type</th>
                                <th class="py-2 pr-4 font-semibold">Report Period</th>
                                <th class="py-2 pr-0 font-semibold">Patient</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="border-b border-slate-100">
                                <td class="py-2 pr-4">{{ $clinicName }}</td>
                                <td class="py-2 pr-4">Patient Medical Record</td>
                                <td class="py-2 pr-4">{{ $reportPeriodLabel }}</td>
                                <td class="py-2 pr-0">{{ $patient->firstname ?? '' }} {{ $patient->lastname ?? '' }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 2. PATIENT INFORMATION ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">2. PATIENT INFORMATION</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.84rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.72rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-4 font-semibold">Field</th>
                                <th class="py-2 pr-0 font-semibold">Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $birthdate = $patient->birthdate ? Carbon\Carbon::parse($patient->birthdate) : null;
                                $age = $birthdate ? $birthdate->age : null;
                            @endphp
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Patient ID</td><td class="py-2 pr-0">{{ $patient->user_id }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Full Name</td><td class="py-2 pr-0">{{ $patient->firstname ?? '' }} {{ $patient->middlename ?? '' }} {{ $patient->lastname ?? '' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Birthdate</td><td class="py-2 pr-0">{{ $birthdate ? $birthdate->format('F j, Y') : '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Age</td><td class="py-2 pr-0">{{ $age ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Sex</td><td class="py-2 pr-0">{{ $patient->sex ? ucfirst($patient->sex) : '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Civil Status</td><td class="py-2 pr-0">{{ $patient->civil_status ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Nationality</td><td class="py-2 pr-0">{{ $patient->nationality ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Occupation</td><td class="py-2 pr-0">{{ $patient->occupation ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Contact Number</td><td class="py-2 pr-0">{{ $patient->contact_number ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Email</td><td class="py-2 pr-0">{{ $patient->email ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Address</td><td class="py-2 pr-0">{{ $patient->address ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">PhilHealth Number</td><td class="py-2 pr-0">{{ $patient->philhealth_number ?? '-' }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4 font-medium">Emergency Contact</td><td class="py-2 pr-0">{{ $patient->emergency_contact ?? '-' }}</td></tr>
                            <tr><td class="py-2 pr-4 font-medium">Emergency Contact Number</td><td class="py-2 pr-0">{{ $patient->emergency_contact_number ?? '-' }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 3. MEDICAL BACKGROUND ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">3. MEDICAL BACKGROUND</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    @php
                        $categoryLabels = [
                            'allergy_food' => 'Food Allergy',
                            'allergy_drug' => 'Drug Allergy',
                            'condition' => 'Condition',
                        ];
                    @endphp
                    <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-4 font-semibold">Category</th>
                                <th class="py-2 pr-4 font-semibold">Medical Information</th>
                                <th class="py-2 pr-0 font-semibold">Notes</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($medicalBackgrounds as $mb)
                                <tr class="border-b border-slate-100 last:border-0">
                                    <td class="py-2 pr-4">{{ $categoryLabels[$mb->category] ?? ucfirst(str_replace('_', ' ', $mb->category)) }}</td>
                                    <td class="py-2 pr-4">{{ $mb->name ?? '-' }}</td>
                                    <td class="py-2 pr-0">{{ $mb->notes ?? '-' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="py-3 text-slate-500">No medical background records found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 4. APPOINTMENT HISTORY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">4. APPOINTMENT HISTORY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.75rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.66rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-3 font-semibold">Date</th>
                                <th class="py-2 pr-3 font-semibold">Time</th>
                                <th class="py-2 pr-3 font-semibold">Doctor</th>
                                <th class="py-2 pr-3 font-semibold">Service</th>
                                <th class="py-2 pr-0 font-semibold">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($appointments as $apt)
                                <tr class="border-b border-slate-100 last:border-0">
                                    <td class="py-2 pr-3 whitespace-nowrap">{{ $apt->appointment_datetime ? Carbon\Carbon::parse($apt->appointment_datetime)->format('M j, Y') : '-' }}</td>
                                    <td class="py-2 pr-3 whitespace-nowrap">{{ $apt->appointment_datetime ? Carbon\Carbon::parse($apt->appointment_datetime)->format('g:i A') : '-' }}</td>
                                    <td class="py-2 pr-3">{{ $apt->doctor ? ($apt->doctor->firstname ?? '').' '.($apt->doctor->lastname ?? '') : '-' }}</td>
                                    <td class="py-2 pr-3">{{ $apt->services && $apt->services->count() ? $apt->services->pluck('service_name')->implode(', ') : '-' }}</td>
                                    <td class="py-2 pr-0">{{ $apt->status ? ucfirst($apt->status) : '-' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="py-3 text-slate-500">No appointments found in the selected period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 5. CONSULTATION / VISIT HISTORY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">5. CONSULTATION / VISIT HISTORY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.75rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.66rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-3 font-semibold">Visit Date</th>
                                <th class="py-2 pr-3 font-semibold">Doctor</th>
                                <th class="py-2 pr-3 font-semibold">Services</th>
                                <th class="py-2 pr-0 font-semibold">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($completedVisits as $visit)
                                @php $apt = $visit->appointment; @endphp
                                <tr class="border-b border-slate-100 last:border-0">
                                    <td class="py-2 pr-3 whitespace-nowrap">{{ $visit->transaction_datetime ? Carbon\Carbon::parse($visit->transaction_datetime)->format('M j, Y') : '-' }}</td>
                                    <td class="py-2 pr-3">{{ $apt && $apt->doctor ? ($apt->doctor->firstname ?? '').' '.($apt->doctor->lastname ?? '') : '-' }}</td>
                                    <td class="py-2 pr-3">{{ $apt && $apt->services && $apt->services->count() ? $apt->services->pluck('service_name')->implode(', ') : '-' }}</td>
                                    <td class="py-2 pr-0">{{ $visit->payment_status ? ucfirst($visit->payment_status) : 'Completed' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="py-3 text-slate-500">No completed visits found in the selected period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 6. PRESCRIPTION HISTORY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">6. PRESCRIPTION HISTORY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.75rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.66rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-3 font-semibold">Date</th>
                                <th class="py-2 pr-3 font-semibold">Doctor</th>
                                <th class="py-2 pr-3 font-semibold">Medication</th>
                                <th class="py-2 pr-3 font-semibold">Dosage</th>
                                <th class="py-2 pr-0 font-semibold">Duration</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($prescriptions as $rx)
                                @foreach ($rx->items as $item)
                                    <tr class="border-b border-slate-100 last:border-0">
                                        <td class="py-2 pr-3 whitespace-nowrap">{{ $rx->prescribed_datetime ? Carbon\Carbon::parse($rx->prescribed_datetime)->format('M j, Y') : '-' }}</td>
                                        <td class="py-2 pr-3">{{ $rx->doctor ? ($rx->doctor->firstname ?? '').' '.($rx->doctor->lastname ?? '') : '-' }}</td>
                                        <td class="py-2 pr-3">{{ $item->medicine_name ?? '-' }}</td>
                                        <td class="py-2 pr-3">{{ $item->dosage ?? '-' }}</td>
                                        <td class="py-2 pr-0">{{ $item->duration ?? '-' }}</td>
                                    </tr>
                                @endforeach
                            @empty
                                <tr>
                                    <td colspan="5" class="py-3 text-slate-500">No prescriptions found in the selected period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 7. TRANSACTION HISTORY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">7. TRANSACTION HISTORY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.75rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.66rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-3 font-semibold">Date</th>
                                <th class="py-2 pr-3 font-semibold">Transaction</th>
                                <th class="py-2 pr-3 font-semibold text-right">Amount</th>
                                <th class="py-2 pr-3 font-semibold text-right">Discount</th>
                                <th class="py-2 pr-0 font-semibold">Payment Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($transactions as $tx)
                                <tr class="border-b border-slate-100 last:border-0">
                                    <td class="py-2 pr-3 whitespace-nowrap">{{ $tx->transaction_datetime ? Carbon\Carbon::parse($tx->transaction_datetime)->format('M j, Y') : '-' }}</td>
                                    <td class="py-2 pr-3">
                                        @php
                                            $svcNames = $tx->appointment && $tx->appointment->services && $tx->appointment->services->count()
                                                ? $tx->appointment->services->pluck('service_name')->implode(', ')
                                                : 'Consultation';
                                        @endphp
                                        {{ $svcNames }}
                                    </td>
                                    <td class="py-2 pr-3 num whitespace-nowrap">&#8369;{{ number_format((float) ($tx->amount ?? 0), 2) }}</td>
                                    <td class="py-2 pr-3 num whitespace-nowrap">&#8369;{{ number_format((float) ($tx->discount_amount ?? 0), 2) }}</td>
                                    <td class="py-2 pr-0">{{ $tx->payment_status ? ucfirst($tx->payment_status) : '-' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="py-3 text-slate-500">No transactions found in the selected period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                        <tfoot>
                            <tr class="border-t-2 border-slate-300 text-[0.76rem] font-semibold text-slate-900">
                                <td colspan="2" class="py-3 pr-3 text-right">TOTALS</td>
                                <td class="py-3 pr-3 num whitespace-nowrap">&#8369;{{ number_format((float) $transactions->sum('amount'), 2) }}</td>
                                <td class="py-3 pr-3 num whitespace-nowrap">&#8369;{{ number_format((float) $transactions->sum('discount_amount'), 2) }}</td>
                                <td class="py-3 pr-0"></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </section>

            {{-- ===== 8. PATIENT SUMMARY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">8. PATIENT SUMMARY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-4 font-semibold">Metric</th>
                                <th class="py-2 pr-0 font-semibold num">Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Total Appointments</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['total_appointments']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Completed Visits</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['completed_visits']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Cancelled Appointments</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['cancelled_appointments']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Active Medical Conditions</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['active_conditions']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Allergies Recorded</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['allergies_recorded']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Prescriptions Issued</td><td class="py-2 pr-0 num">{{ number_format((int) $summary['prescriptions_issued']) }}</td></tr>
                            <tr><td class="py-2 pr-4">Total Amount Paid</td><td class="py-2 pr-0 num">&#8369;{{ number_format((float) $summary['total_amount_paid'], 2) }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== 9. SIGNATORY ===== --}}
            <div class="mt-10 border-t border-slate-300 pt-8 grid grid-cols-1 md:grid-cols-2 gap-8 text-[0.84rem]">
                <div>
                    <div class="text-slate-600 mb-8">Prepared by:</div>
                    <div class="border-b border-slate-500 w-64 max-w-full"></div>
                    <div class="mt-2 font-semibold text-slate-900">{{ $generatedBy }}</div>
                    <div class="text-slate-600">Administrator</div>
                </div>
                <div class="md:text-right text-slate-600">
                    Generated using {{ $clinicName }} System
                </div>
            </div>
        </div>
    </div>

    <div class="print-page-footer">OPOL MHO | {{ $reportPeriodLabel }}</div>
</body>
</html>
