<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OPOL MHO - Report {{ $reportPeriodLabel }}</title>
    @vite('resources/css/app.css')
    <style>
        @page {
            size: A4 landscape;
            margin: 12mm;
        }

        @media print {
            .no-print { display: none !important; }
            body { background: #fff !important; }
            .report-shell {
                border: 0 !important;
                box-shadow: none !important;
                padding-bottom: 32px !important;
            }
            .print-page-footer {
                display: block !important;
            }
        }

        * {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
        }

        /* Tabular numerals keep stacked currency/counts aligned by digit */
        .num {
            font-variant-numeric: tabular-nums;
            text-align: right;
        }

        .print-page-footer {
            display: none;
            position: fixed;
            bottom: 6mm;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 7.5pt;
            color: #777;
            z-index: 1000;
        }
    </style>
</head>
<body class="min-h-screen bg-slate-100 text-slate-900">
    @unless ($embedded ?? false)
        <div class="no-print sticky top-0 z-10 bg-white/90 backdrop-blur border-b border-slate-200 px-4 py-3">
            <div class="max-w-7xl mx-auto flex items-center justify-between gap-3">
                <div class="text-sm font-semibold text-slate-900">Transaction Report</div>
                <button type="button" onclick="window.print()" class="px-3 py-2 rounded-xl bg-green-900 text-white text-[0.78rem] font-semibold hover:bg-green-800">Print / Save as PDF</button>
            </div>
        </div>
    @endunless

    <div class="max-w-7xl mx-auto p-4 md:p-6">
        <div class="report-shell bg-white border border-slate-200 rounded-3xl p-6 md:p-8">

            {{-- ===== LETTERHEAD ===== --}}
            <div class="border-b-4 border-double border-slate-900 pb-4">
                <div class="flex items-start gap-4">
                    <img src="{{ asset('images/MHOLogoV2.png') }}" alt="{{ $clinicName }} logo"
                         class="letterhead-logo w-16 h-16 object-contain flex-shrink-0 mt-0.5">

                    <div class="flex-1 min-w-0">
                        <div class="text-[0.78rem] font-semibold uppercase tracking-[0.35em] text-slate-500">
                            {{ $clinicName }}
                        </div>
                        <h1 class="mt-1 text-2xl font-bold tracking-wide text-slate-900">TRANSACTION REPORT</h1>
                    </div>
                </div>

                <div class="mt-5 grid grid-cols-1 md:grid-cols-3 gap-4 text-[0.84rem]">
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Report Period</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $reportPeriodLabel }}</div>
                    </div>
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Generated On</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $generatedOn->format('F j, Y') }}</div>
                        <div class="text-slate-600">{{ $generatedOn->format('g:i A') }}</div>
                    </div>
                    <div>
                        <div class="text-[0.72rem] uppercase tracking-widest text-slate-400">Generated By</div>
                        <div class="mt-1 font-semibold text-slate-900">{{ $generatedBy }}</div>
                    </div>
                </div>
            </div>

            {{-- ===== SUMMARY ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">SUMMARY</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.84rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.72rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-4 font-semibold">Metric</th>
                                <th class="py-2 pr-0 font-semibold text-right">Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Total Transactions</td><td class="py-2 pr-0 font-semibold num">{{ number_format((int) $summary['total_transactions']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Paid Transactions</td><td class="py-2 pr-0 font-semibold num">{{ number_format((int) $summary['paid_transactions']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Pending Payments</td><td class="py-2 pr-0 font-semibold num">{{ number_format((int) $summary['pending_payments']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Failed Payments</td><td class="py-2 pr-0 font-semibold num">{{ number_format((int) $summary['failed_payments']) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Gross Revenue</td><td class="py-2 pr-0 font-semibold num">&#8369;{{ number_format((float) $summary['gross_revenue'], 2) }}</td></tr>
                            <tr class="border-b border-slate-100"><td class="py-2 pr-4">Total Discounts</td><td class="py-2 pr-0 font-semibold num">&#8369;{{ number_format((float) $summary['total_discounts'], 2) }}</td></tr>
                            <tr><td class="py-2 pr-4">Net Revenue</td><td class="py-2 pr-0 font-semibold num">&#8369;{{ number_format((float) $summary['net_revenue'], 2) }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </section>

            {{-- ===== DISCOUNT SUMMARY / PAYMENT STATUS ===== --}}
            <div class="mt-6 grid grid-cols-1 xl:grid-cols-2 gap-6">
                <section>
                    <div class="border-b border-slate-300 pb-2">
                        <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">DISCOUNT SUMMARY</h2>
                    </div>
                    <div class="overflow-x-auto mt-3">
                        <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                            <thead>
                                <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                    <th class="py-2 pr-4 font-semibold">Discount Type</th>
                                    <th class="py-2 pr-4 font-semibold text-right">Count</th>
                                    <th class="py-2 pr-0 font-semibold text-right">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($discountSummary as $row)
                                    <tr class="border-b border-slate-100 last:border-0">
                                        <td class="py-2 pr-4">{{ $row['label'] }}</td>
                                        <td class="py-2 pr-4 num">{{ number_format((int) $row['count']) }}</td>
                                        <td class="py-2 pr-0 num">&#8369;{{ number_format((float) $row['total'], 2) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </section>

                <section>
                    <div class="border-b border-slate-300 pb-2">
                        <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">PAYMENT STATUS</h2>
                    </div>
                    <div class="overflow-x-auto mt-3">
                        <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                            <thead>
                                <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                    <th class="py-2 pr-4 font-semibold">Status</th>
                                    <th class="py-2 pr-0 font-semibold text-right">Count</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($paymentStatusSummary as $row)
                                    <tr class="border-b border-slate-100 last:border-0">
                                        <td class="py-2 pr-4">{{ $row['label'] }}</td>
                                        <td class="py-2 pr-0 num">{{ number_format((int) $row['count']) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>

            {{-- ===== REVENUE BREAKDOWN / DAILY REVENUE ===== --}}
            <div class="mt-6 grid grid-cols-1 xl:grid-cols-2 gap-6">
                <section>
                    <div class="border-b border-slate-300 pb-2">
                        <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">REVENUE BREAKDOWN</h2>
                    </div>
                    <div class="overflow-x-auto mt-3">
                        <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                            <thead>
                                <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                    <th class="py-2 pr-4 font-semibold">Payment Mode</th>
                                    <th class="py-2 pr-4 font-semibold text-right">Transactions</th>
                                    <th class="py-2 pr-0 font-semibold text-right">Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($paymentModeSummary as $row)
                                    <tr class="border-b border-slate-100 last:border-0">
                                        <td class="py-2 pr-4">{{ $row['label'] }}</td>
                                        <td class="py-2 pr-4 num">{{ number_format((int) $row['transactions']) }}</td>
                                        <td class="py-2 pr-0 num">&#8369;{{ number_format((float) $row['revenue'], 2) }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3" class="py-3 text-slate-500">No paid transactions in the selected period.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </section>

                <section>
                    <div class="border-b border-slate-300 pb-2">
                        <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">DAILY REVENUE</h2>
                    </div>
                    <div class="overflow-x-auto mt-3">
                        <table class="min-w-full text-left text-[0.82rem] text-slate-700">
                            <thead>
                                <tr class="border-b border-slate-200 text-[0.7rem] uppercase tracking-widest text-slate-400">
                                    <th class="py-2 pr-4 font-semibold">Date</th>
                                    <th class="py-2 pr-4 font-semibold text-right">Transactions</th>
                                    <th class="py-2 pr-0 font-semibold text-right">Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($dailyRevenue as $row)
                                    <tr class="border-b border-slate-100 last:border-0">
                                        <td class="py-2 pr-4">{{ $row['date_label'] }}</td>
                                        <td class="py-2 pr-4 num">{{ number_format((int) $row['transactions']) }}</td>
                                        <td class="py-2 pr-0 num">&#8369;{{ number_format((float) $row['revenue'], 2) }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3" class="py-3 text-slate-500">No daily revenue available for this period.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>

            {{-- ===== TRANSACTION DETAILS ===== --}}
            <section class="mt-6">
                <div class="border-b border-slate-300 pb-2">
                    <h2 class="text-sm font-bold tracking-[0.2em] text-slate-900">TRANSACTION DETAILS</h2>
                </div>
                <div class="overflow-x-auto mt-3">
                    <table class="min-w-full text-left text-[0.75rem] text-slate-700">
                        <thead>
                            <tr class="border-b border-slate-200 text-[0.66rem] uppercase tracking-widest text-slate-400">
                                <th class="py-2 pr-3 font-semibold">ID</th>
                                <th class="py-2 pr-3 font-semibold">Date</th>
                                <th class="py-2 pr-3 font-semibold">Patient</th>
                                <th class="py-2 pr-3 font-semibold">Doctor</th>
                                <th class="py-2 pr-3 font-semibold">Services</th>
                                <th class="py-2 pr-3 font-semibold text-right">Amount</th>
                                <th class="py-2 pr-3 font-semibold text-right">Discount</th>
                                <th class="py-2 pr-3 font-semibold text-right">Net</th>
                                <th class="py-2 pr-3 font-semibold">Status</th>
                                <th class="py-2 pr-0 font-semibold">Mode</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($transactionRows as $row)
                                <tr class="border-b border-slate-100 align-top last:border-0">
                                    <td class="py-2 pr-3 font-semibold text-slate-900">#{{ $row['transaction_id'] }}</td>
                                    <td class="py-2 pr-3 whitespace-nowrap">{{ $row['date_label'] }}</td>
                                    <td class="py-2 pr-3">{{ $row['patient_name'] }}</td>
                                    <td class="py-2 pr-3">{{ $row['doctor_name'] }}</td>
                                    <td class="py-2 pr-3">{{ count($row['services']) ? implode(', ', $row['services']) : '-' }}</td>
                                    <td class="py-2 pr-3 whitespace-nowrap num">&#8369;{{ number_format((float) $row['amount'], 2) }}</td>
                                    <td class="py-2 pr-3">
                                        <div class="text-right">{{ $row['discount_type'] }}</div>
                                        <div class="text-slate-500 whitespace-nowrap num">&#8369;{{ number_format((float) $row['discount_amount'], 2) }}</div>
                                    </td>
                                    <td class="py-2 pr-3 whitespace-nowrap num">&#8369;{{ number_format((float) $row['net_amount'], 2) }}</td>
                                    <td class="py-2 pr-3">{{ $row['status'] }}</td>
                                    <td class="py-2 pr-0">{{ $row['payment_mode'] }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="10" class="py-4 text-center text-slate-500">No transactions found for the selected report period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                        <tfoot>
                            <tr class="border-t-2 border-slate-300 text-[0.76rem] font-semibold text-slate-900">
                                <td colspan="5" class="py-3 pr-3 text-right">TOTALS</td>
                                <td class="py-3 pr-3 whitespace-nowrap num">&#8369;{{ number_format((float) $summary['gross_revenue'], 2) }}</td>
                                <td class="py-3 pr-3 whitespace-nowrap num">&#8369;{{ number_format((float) $summary['total_discounts'], 2) }}</td>
                                <td class="py-3 pr-3 whitespace-nowrap num">&#8369;{{ number_format((float) $summary['net_revenue'], 2) }}</td>
                                <td colspan="2" class="py-3 pr-0"></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </section>

            {{-- ===== FOOTER / SIGNATORY ===== --}}
            <div class="mt-10 border-t border-slate-300 pt-8 grid grid-cols-1 md:grid-cols-2 gap-8 text-[0.84rem]">
                <div>
                    <div class="text-slate-600 mb-8">Prepared by:</div>
                    <div class="border-b border-slate-500 w-64 max-w-full"></div>
                    <div class="mt-2 font-semibold text-slate-900">{{ $generatedBy }}</div>
                    <div class="text-slate-600">Administrator</div>
                </div>
                <div class="md:text-right text-slate-600">
                    Generated using {{ $clinicName }} System
                </div>
            </div>
        </div>
    </div>

    <div class="print-page-footer">OPOL MHO | {{ $reportPeriodLabel }}</div>
</body>
</html>